clusters:
- in-cluster
project: default
repoURL: https://gitlab.com/6shore.net/kad.git
namespace: kad
autosync: false

kad:
  image: tomkukral/kad
  replicas: 2

  ingress:
    enabled: true
    clusterhost: kad.6shore.net

  service:
    type: ClusterIP
    ipFamilyPolicy: PreferDualStack


  rbac:
    enabled: false

  prometheus:
    enabled: true
