apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argo
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: "metrics-server-1"
    spec:
      project: default
      source:
        repoURL: https://github.com/tomkukral/kubernetes-examples
        targetRevision: HEAD
        path: metrics-server
      destination:
        server: "1"
        namespace: kube-system
